includes = ["avilla/elizabeth"]
raw-dependencies = [
  "avilla-core >= 1.0.0a26",
  "avilla-standard-qq >= 1.0.0a21"
]

[project]
name = "avilla-elizabeth"
version = "1.0.0a33" # WIP for release.
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = [
  "aiohttp"
]
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"